### PR TITLE
ppx_sexp_conv >= v0.11 has a runtime dependency

### PR DESCRIPTION
**Pull request by ghost**
See [this comment](https://github.com/ocaml/opam-repository/pull/11901#issuecomment-386567425) for details

### CODE REVIEW

**Comment by yminsky** [comment]
@samoht do you want to look at this?

**Comment by samoht** [comment]
I haven't looked at the details bit this seems a bit unfortunate :-(

**Comment by ghost** [comment]
Sorry, why is this unfortunate? It's more hygienic for ppx rewriters to usr a runtime library. Do you kbow what is the effect of marking a dependency as build only btw?

**Comment by samoht** [comment]
`{build}` means that the package won't be recompiled if the dependency changes (because you don't link with anything in that package). Which means that updating `ppx_sexp_conv` will now trigger a lot of recompilations.

I understand the rational of your change. By "unfortunate" I just meant it will be harder to check if a dependency is properly tagged as `build` or if it was forgotten by the developer (previously the rule was simply: start by `ppx` or is a build tool implies `build`). Now the repo maintainers (and the tooling) need to have extra knowledge to get this right.

**Comment by ghost** [comment]
> {build} means that the package won't be recompiled if the dependency changes (because you don't link with anything in that package). Which means that updating ppx_sexp_conv will now trigger a lot of recompilations.

Hmm, ppx rewriters should never be flagged as build dependency then, even when they don't have runtime dependencies. If the code they generate changes, all reverse dependencies need to be rebuilt as well.

**Pull request merged**
