### PR TITLE
Port to jbuilder and expose a library

### PR DESCRIPTION
**Pull request by avsm**
The jbuilder port rearranges the build tree to install a library with the Parts interfaces that can be used by external tools such as RWO.

This PR doesn't currently do anything with ppx-ignore as I'm not sure where it's used or why it's included with topexpect.  Can be integrated easily once it's clear what library it should be in.

### CODE REVIEW

**Comment by avsm** [comment]
This also adds a Travis CI test, if you can enable that @let-def

**Comment by let-def** [comment]
I am fine with that. I talked with Jeremie about relaxing the check with JaneStreet ppx, ppx-ignore should no longer be useful.

**Comment by avsm** [comment]
thanks, ccing @yminsky @diml on this as we need it for RWO.  Will the relaxed ppx check be in a stable release of Core in the next few months (we are basing the book on v0.9.x at the moment).

**Comment by let-def** [comment]
For @diml: ppx-ignore was a ppx rewriter that removed attributes when invoked from merlin to pass the checks. It was just a workaround.

**Comment by avsm** [comment]
@let-def what invokes ppx-ignore -- is it something in RWO or directly from merlin? I'm thinking it would be good to package it up as part of this jbuilder port in the short term, so it needs to be installed somewhere.  That would unblock RWO immediately.

**Comment by ghost** [comment]
@xclerc is looking at replacing the errors by pre-processor warnings. This will solve this issue. We can backport the changes once they reach github.

**Comment by avsm** [comment]
sgtm, thanks!

**Pull request merged**
